### ISSUE TITLE
fairing version requirements has conflict with kfp on kubernetes

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/examples#770]
failing on both master branch and v1: `AttributeError: type object 'V1Container' has no attribute 'swagger_types '`

seems like to be some kind of version mismatch?

**Comment by Ark-kun** [comment]
There was a major breaking change in the Kubernetes package: https://github.com/kubernetes-client/python/pull/995

**Comment by Ark-kun** [comment]
KFP SDK requires kubernetes <= 10.0.0, so something re-installs a higher version.

**Comment by gabrielwen** [comment]
```
Traceback (most recent call last):
  File "execute_notebook.py", line 56, in <module>
    run_notebook_test(NOTEBOOK_ABS_PATH, EXPECTED_MGS)
  File "execute_notebook.py", line 26, in run_notebook_test
    output_path = execute_notebook(notebook_path, parameters=parameters)
  File "execute_notebook.py", line 22, in execute_notebook
    log_output=True)
  File "/usr/local/lib/python3.6/dist-packages/papermill/execute.py", line 108, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/usr/local/lib/python3.6/dist-packages/papermill/execute.py", line 194, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError:
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-7ce12ce90360> in <module>
      1 # Imports not to be included in the built docker image
      2 import util
----> 3 import kfp
      4 import kfp.components as comp
      5 import kfp.gcp as gcp

~/.local/lib/python3.6/site-packages/kfp/__init__.py in <module>
     16 __version__ = '0.1.32'
     17
---> 18 from . import components
     19 from . import containers
     20 from . import dsl

~/.local/lib/python3.6/site-packages/kfp/components/__init__.py in <module>
     13 # limitations under the License.
     14
---> 15 from ._airflow_op import *
     16 from ._components import *
     17 from ._python_op import *

~/.local/lib/python3.6/site-packages/kfp/components/_airflow_op.py in <module>
     21 from typing import List
     22
---> 23 from ._python_op import _func_to_component_spec, _create_task_factory_from_component_spec
     24
     25

~/.local/lib/python3.6/site-packages/kfp/components/_python_op.py in <module>
     28
     29 from ._yaml_utils import dump_yaml
---> 30 from ._components import _create_task_factory_from_component_spec
     31 from ._data_passing import serialize_value, type_name_to_deserializer, type_name_to_serializer, type_to_type_name
     32 from ._naming import _make_name_unique_by_adding_index

~/.local/lib/python3.6/site-packages/kfp/components/_components.py in <module>
     27 from ._structures import *
     28 from ._data_passing import serialize_value, type_name_to_type
---> 29 from kfp.dsl import PipelineParam
     30 from kfp.dsl.types import verify_type_compatibility
     31

~/.local/lib/python3.6/site-packages/kfp/dsl/__init__.py in <module>
     15
     16 from ._pipeline_param import PipelineParam, match_serialized_pipelineparam
---> 17 from ._pipeline import Pipeline, pipeline, get_pipeline_conf, PipelineConf
     18 from ._container_op import ContainerOp, InputArgumentPath, UserContainer, Sidecar
     19 from ._resource_op import ResourceOp

~/.local/lib/python3.6/site-packages/kfp/dsl/_pipeline.py in <module>
     14
     15
---> 16 from . import _container_op
     17 from . import _resource_op
     18 from . import _ops_group

~/.local/lib/python3.6/site-packages/kfp/dsl/_container_op.py in <module>
     94
     95
---> 96 class Container(V1Container):
     97     """
     98     A wrapper over k8s container definition object (io.k8s.api.core.v1.Container),

~/.local/lib/python3.6/site-packages/kfp/dsl/_container_op.py in Container()
    139     swagger_types = {
    140         key: value
--> 141         for key, value in V1Container.swagger_types.items() if key != 'name'
    142     }
    143     attribute_map = {

AttributeError: type object 'V1Container' has no attribute 'swagger_types'
```

**Comment by Ark-kun** [comment]
Yes, this is the breaking change in Kubernetes that I've mentioned.
The environment seems to be incorrect (KFP requires kubernetes <= 10, but this environment has kubernetes == 11).
Can you tell me more about the environment?

**Comment by gabrielwen** [comment]
thanks, that makes sense now.  it looks like kfp installs kubernetes client in 0.9.0, but later on fairing installs a newer version:
```
Collecting kubernetes>=10.0.1
  Downloading https://files.pythonhosted.org/packages/59/46/d4b9364fcab59b5f9248e014c7592df8de84ad6548a6fe3de2d805bb75fc/kubernetes-11.0.0-py3-none-any.whl (1.5MB)
```

@abhi-g could you help triage this to fairing folks?

**Comment by abhi-g** [comment]
what's the recommended version of k8s client that we should be using?

**Comment by abhi-g** [comment]
looks like the intersection of what kfp requires and what fairing can work with leaves 10.0.1 as the only acceptable version.

**Comment by jinchihe** [comment]
I think we can update KFP reqs kubenertes Client to 10.0.1?

**Comment by gabrielwen** [comment]
@Ark-kun do you think it's faster to make the sdk compatible with v11+ or change the requirement to be 10.0.1?

**Comment by jinchihe** [comment]
There is a [defect](https://github.com/kubernetes-client/python/issues/1112) in the kubenertes Client 11.0.0, I do not suggest to 11.0.0 @gabrielwen

**Comment by jlewi** [comment]
@gabrielwen @jinchihe @Ark-kun when did the test last pass? Can we pin the test to use whatever versions of fairing, kfp sdk etc.. that were used then?

**Comment by oakkas** [comment]
I didn't understand, what is the solution on this error.
